services:
  service-discovery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: service-discovery
        JAR_NAME: service-discovery-1.0.0.jar
    ports:
      - "8761:8761"
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: config-server
        JAR_NAME: config-server-1.0.0.jar
    ports:
      - "8888:8888"
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  postgres-user:
    image: postgres:17
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-user:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: user-service
        JAR_NAME: user-service-1.0.0.jar
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      USER_DB_URL: r2dbc:postgresql://postgres-user:5432/userdb
      USER_DB_JDBC_URL: jdbc:postgresql://postgres-user:5432/userdb
      USER_DB_USER: postgres
      USER_DB_PASS: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    depends_on:
      postgres-user:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - bank-network

  postgres-product:
    image: postgres:17
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata-product:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: product-service
        JAR_NAME: product-service-1.0.0.jar
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      PRODUCT_DB_URL: jdbc:postgresql://postgres-product:5432/productdb
      PRODUCT_DB_USER: postgres
      PRODUCT_DB_PASS: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    depends_on:
      postgres-product:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - bank-network

  postgres-assignment:
    image: postgres:17
    environment:
      POSTGRES_DB: assignmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata-assignment:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  assignment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: assignment-service
        JAR_NAME: assignment-service-1.0.0.jar
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      ASSIGNMENT_DB_URL: jdbc:postgresql://postgres-assignment:5432/assignmentdb
      ASSIGNMENT_DB_USER: postgres
      ASSIGNMENT_DB_PASS: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    depends_on:
      postgres-assignment:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - bank-network

  postgres-app:
    image: postgres:17
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata-app:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  application-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: application-service
        JAR_NAME: application-service-1.0.0.jar
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      APP_DB_URL: jdbc:postgresql://postgres-app:5432/appdb
      APP_DB_USER: postgres
      APP_DB_PASS: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    depends_on:
      postgres-app:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - bank-network

  postgres-tag:
    image: postgres:17
    environment:
      POSTGRES_DB: tagdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - pgdata-tag:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tag-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: tag-service
        JAR_NAME: tag-service-1.0.0.jar
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      TAG_DB_URL: jdbc:postgresql://postgres-tag:5432/tagdb
      TAG_DB_USER: postgres
      TAG_DB_PASS: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    depends_on:
      postgres-tag:
        condition: service_healthy
      config-server:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - bank-network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: gateway
        JAR_NAME: gateway-1.0.0.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      application-service:
        condition: service_started
      assignment-service:
        condition: service_started
      tag-service:
        condition: service_started
    networks:
      - bank-network

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"  # Добавляем порт для контроллера
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: "4t5LzWXDSqqY7EsBkQzXgw"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"  # Меняем на localhost
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # Для разработки - ускоряем запуск
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 20s  # Увеличиваем таймаут
      retries: 15   # Увеличиваем количество попыток
      start_period: 60s  # Увеличиваем начальный период
    networks:
      bank-network:
        aliases:
          - kafka1
          - kafka2
          - kafka3  # Добавляем алиасы для всех нод

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9094:9092"
      - "9095:9093"  # Добавляем порт для контроллера
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 2
      KAFKA_CLUSTER_ID: "4t5LzWXDSqqY7EsBkQzXgw"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9094"  # Используем mapped порт
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 60s
    networks:
      bank-network:
        aliases:
          - kafka1
          - kafka2
          - kafka3

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9096:9092"
      - "9097:9093"  # Добавляем порт для контроллера
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 3
      KAFKA_CLUSTER_ID: "4t5LzWXDSqqY7EsBkQzXgw"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9096"  # Используем mapped порт
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 60s
    networks:
      bank-network:
        aliases:
          - kafka1
          - kafka2
          - kafka3

networks:
  bank-network:
    driver: bridge

volumes:
  pgdata-user:
  pgdata-product:
  pgdata-assignment:
  pgdata-app:
  pgdata-tag: